version: 2
registries:
  dockerhub:
    type: docker-registry
    url: registry.hub.docker.com
    username: ${{ secrets.DOCKERHUB_USERNAME }}
    password: ${{ secrets.DOCKERHUB_TOKEN }}
updates:
  # Maintain dependencies for GitHub Actions.
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "lauwarm"
    assignees:
      - "lauwarm"
  - package-ecosystem: "docker"
    directory: "/"
    registries:
      - dockerhub
    schedule:
      interval: "daily"
    reviewers:
      - "lauwarm"
    assignees:
      - "lauwarm"
